/*
 * File: app/view/pnlNuevoMuestraViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('plasma.view.pnlNuevoMuestraViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.pnlnuevomuestra',

    onCbInstitucionSelect: function(combo, record, eOpts) {
        Ext.Ajax.request({
            method: 'post',
            url: '../servidor/plasma/muestra/getcodigo',
            success: function (response, options) {
                var responseData = Ext.JSON.decode(response.responseText);
                Ext.getCmp('txtCodInstitucional').setValue(responseData.data[0].codigo);
            }
        });
    },

    onBtnKitMasClick: function(button, e, eOpts) {
        var panel = Ext.create('Ext.panel.Panel', {
            margin: '10 10 10 10',
            layout : {
                type  : 'vbox',
                pack  : 'center',
                align : 'middle'
            },

            items:[

            {
                xtype: 'combobox',
                id: 'cbKitM'+I,
                fieldLabel: 'Kit',
                name: 'kit',
                allowBlank: false,
                editable: false,
                displayField: 'nombre',
                queryMode: 'local',
                store: 'Kit',
                valueField: 'id',
                labelStyle: 'font-weight:bold',
            },
            {
                xtype: 'textfield',
                id: 'txtAbsCoi'+I,
                fieldLabel: 'Abs/Coi',
                name: 'abs_coi',
                allowBlank: false,
                labelStyle: 'font-weight:bold',
            }

            ],
            renderTo: Ext.getBody()
        });

        I=I+1;
        Ext.getCmp('frmRecepcion1').add(panel);
    },

    onBtnKitMenosClick: function(button, e, eOpts) {
        if(I === 0){
            Ext.Msg.alert('Atención','Debe ingresar al menos un kit');
        }
        else{
            I--;
            Ext.getCmp('cbKitM'+I).destroy();
            Ext.getCmp('txtAbsCoi'+I).destroy();
        }

    },

    onBtnMarcadorMasClick: function(button, e, eOpts) {
        var panel = Ext.create('Ext.panel.Panel', {
            margin: '10 10 10 10',
            layout : {
                type  : 'vbox',
                pack  : 'center',
                align : 'middle'
            },

            items:[

            {
                xtype: 'combobox',
                id: 'cbMarcador'+I,
                fieldLabel: 'Marcador Serológico',
                name: 'marcador',
                allowBlank: false,
                editable: false,
                displayField: 'nombre',
                queryMode: 'local',
                store: 'Marcador',
                valueField: 'id',
                labelStyle: 'font-weight:bold',
            },
            /*{
            xtype: 'textfield',
            id: 'txtAbsCol'+I,
            fieldLabel: 'Abs/COl',
            name: 'abs_co',
            allowBlank: false,
            labelStyle: 'font-weight:bold',
            }*/

            ],
            renderTo: Ext.getBody()
        });

        I=I+1;
        Ext.getCmp('frmRecepcion2').add(panel);
    },

    onBtnMarcadorMenosClick: function(button, e, eOpts) {
        if(I === 0){
            Ext.Msg.alert('Atención','Debe ingresar al menos un marcador');
        }
        else{
            I--;
            Ext.getCmp('cbMarcador'+I).destroy();
            //Ext.getCmp('txtAbsCol'+I).destroy();
        }


    },

    onBtnGuardarMuestraClick: function(button, e, eOpts) {

        var forma = Ext.getCmp('frmRecepcion').getForm();
        var forma1 = Ext.getCmp('frmRecepcion1').getForm();
        var forma2 = Ext.getCmp('frmRecepcion2').getForm();
        if(forma.isValid() && forma1.isValid() && forma2.isValid()){


            Ext.Ajax.request({
                url: '../servidor/plasma/muestra/verificar',
                method:"post",
                params: {

                    muestra: ID
                },
                success: function( result, request ) {
                    var responseData = Ext.JSON.decode(result.responseText);
                    if(responseData.success)
                    {
                        var me = this;
                        var forma = Ext.getCmp('frmRecepcion').getForm();

                        if (forma.isValid()) {
                            var values = forma.getValues();
                            Ext.Ajax.request({
                                url: '../servidor/plasma/muestra/updatemuestra',
                                method:"post",
                                params: {
                                    muestra: ID,
                                    data: Ext.encode(values),
                                },
                                success: function( result, request ) {
                                    var responseData = Ext.JSON.decode(result.responseText);


                                    if(responseData.success)
                                    {

                                        var forma1 = Ext.getCmp('frmRecepcion1').getForm();

                                        if (forma1.isValid()) {
                                            var values1 = forma1.getValues();
                                            Ext.Ajax.request({
                                                url: '../servidor/plasma/muestrakit/update',
                                                method:"post",
                                                params: {
                                                    data: Ext.encode(values1),
                                                    id: ID
                                                },
                                                success: function( result, request ) {
                                                    var responseData = Ext.JSON.decode(result.responseText);
                                                    if(responseData.success)
                                                    {

                                                    }
                                                    else
                                                    {
                                                        Ext.Msg.alert('Alerta','Faltan datos');
                                                    }
                                                },

                                                failure: function(response, opts) {
                                                    console.log('server-side failure with status code ' + response.status);
                                                }
                                            });

                                        }
                                        else
                                        {
                                            Ext.Msg.alert('Atención','Los datos son incorrectos o se encuentran incompletos');

                                        }
                                        var forma2 = Ext.getCmp('frmRecepcion2').getForm();

                                        if (forma2.isValid()) {
                                            var values2 = forma2.getValues();
                                            Ext.Ajax.request({
                                                url: '../servidor/plasma/muestramarcador/update',
                                                method:"post",
                                                params: {
                                                    data: Ext.encode(values2),
                                                    id: ID
                                                },
                                                success: function( result, request ) {
                                                    var responseData = Ext.JSON.decode(result.responseText);
                                                    if(responseData.success)
                                                    {

                                                    }
                                                    else
                                                    {
                                                        Ext.Msg.alert('Alerta','Faltan datos');
                                                    }
                                                },

                                                failure: function(response, opts) {
                                                    console.log('server-side failure with status code ' + response.status);
                                                }
                                            });

                                        }
                                        else
                                        {
                                            Ext.Msg.alert('Atención','Los datos son incorrectos o se encuentran incompletos');

                                        }


                                        Ext.Msg.alert('Aviso','Se ha actualizado la muestra');


                                    }
                                    else
                                    {
                                        Ext.Msg.alert('Alerta','Faltan datos');
                                    }
                                },

                                failure: function(response, opts) {
                                    console.log('server-side failure with status code ' + response.status);
                                }
                            });

                        }
                        else
                        {
                            Ext.Msg.alert('Atención','Los datos son incorrectos o se encuentran incompletos');

                        }
                    }
                    else
                    {
                        var me = this;
                        var forma = Ext.getCmp('frmRecepcion').getForm();

                        if (forma.isValid()) {
                            var values = forma.getValues();
                            Ext.Ajax.request({
                                url: '../servidor/plasma/muestra/guardar',
                                method:"post",
                                params: {
                                    data: Ext.encode(values),
                                },
                                success: function( result, request ) {
                                    var responseData = Ext.JSON.decode(result.responseText);
                                    if(responseData.success)
                                    {
                                        Ext.Ajax.request({
                                            url: '../servidor/plasma/muestra/getUltimo',
                                            method:"post",
                                            success: function( result, request ) {
                                                var responseData = Ext.JSON.decode(result.responseText);
                                                if(responseData.success)
                                                {
                                                    ID = responseData.data[0].ultimo;
                                                    var forma1 = Ext.getCmp('frmRecepcion1').getForm();

                                                    if (forma1.isValid()) {
                                                        var values1 = forma1.getValues();
                                                        Ext.Ajax.request({
                                                            url: '../servidor/plasma/muestrakit/guardar',
                                                            method:"post",
                                                            params: {
                                                                data: Ext.encode(values1),
                                                                id: ID
                                                            },
                                                            success: function( result, request ) {
                                                                var responseData = Ext.JSON.decode(result.responseText);
                                                                if(responseData.success)
                                                                {

                                                                }
                                                                else
                                                                {
                                                                    Ext.Msg.alert('Alerta','Faltan datos');
                                                                }
                                                            },

                                                            failure: function(response, opts) {
                                                                console.log('server-side failure with status code ' + response.status);
                                                            }
                                                        });

                                                    }
                                                    else
                                                    {
                                                        Ext.Msg.alert('Atención','Los datos son incorrectos o se encuentran incompletos');

                                                    }
                                                    var forma2 = Ext.getCmp('frmRecepcion2').getForm();

                                                    if (forma2.isValid()) {
                                                        var values2 = forma2.getValues();
                                                        Ext.Ajax.request({
                                                            url: '../servidor/plasma/muestramarcador/guardar',
                                                            method:"post",
                                                            params: {
                                                                data: Ext.encode(values2),
                                                                id: ID
                                                            },
                                                            success: function( result, request ) {
                                                                var responseData = Ext.JSON.decode(result.responseText);
                                                                if(responseData.success)
                                                                {

                                                                }
                                                                else
                                                                {
                                                                    Ext.Msg.alert('Alerta','Faltan datos');
                                                                }
                                                            },

                                                            failure: function(response, opts) {
                                                                console.log('server-side failure with status code ' + response.status);
                                                            }
                                                        });

                                                    }
                                                    else
                                                    {
                                                        Ext.Msg.alert('Atención','Los datos son incorrectos o se encuentran incompletos');

                                                    }
                                                    Ext.getCmp('tabPanel').down('#tab1').setDisabled(false);
                                                    Ext.Msg.alert('Aviso','Se ha guardado la muestra');



                                                }
                                                else
                                                {
                                                    Ext.Msg.alert('Alerta','Error');
                                                }
                                            },

                                            failure: function(response, opts) {
                                                console.log('server-side failure with status code ' + response.status);
                                            }
                                        });


                                    }
                                    else
                                    {
                                        Ext.Msg.alert('Alerta','Faltan datos');
                                    }
                                },

                                failure: function(response, opts) {
                                    console.log('server-side failure with status code ' + response.status);
                                }
                            });

                        }
                        else
                        {
                            Ext.Msg.alert('Atención','Los datos son incorrectos o se encuentran incompletos');

                        }
                    }
                },

                failure: function(response, opts) {
                    console.log('server-side failure with status code ' + response.status);
                }
            });
        }
        else
        {
            Ext.Msg.alert('Atención','Los datos son incorrectos o se encuentran incompletos');
        }
    },

    onBtnCancelarMuestraClick: function(button, e, eOpts) {
        if(!Ext.getCmp('pnlMuestras'))
        {
            Ext.getCmp('pnlCentral').removeAll();
            var win = Ext.create('plasma.view.pnlMuestras');
            Ext.getCmp('pnlCentral').add(win);
            win.show();
            var strMuestra = Ext.getStore('Muestra');
            strMuestra.removeAll();

            strMuestra.load();
        }
    },

    onTabActivate: function(tab, eOpts) {
        var store = Ext.getStore('Pruebas');

        store.proxy.extraParams={
            bandera :2,
            id:ID
        };
        store.load();

        var strMarcador = Ext.getStore('Marcador');
        strMarcador.proxy.extraParams={
            bandera :1
        };
        strMarcador.load();

        var strKit = Ext.getStore('Kit');

        strKit.proxy.extraParams={
            bandera :1
        };
        strKit.load();
    },

    onBtnAgregarSueroClick1: function(button, e, eOpts) {
        if(ID=== 'null'){
            Ext.Msg.alert('Aviso','Debe realizar primero la recepción de la muestra');
        }
        else{
            var forma = Ext.getCmp('frmPlasma').getForm(),
                store = Ext.getStore('Pruebas');
            if (forma.isValid()) {
                var values = forma.getValues();
                Ext.Ajax.request({
                    url: '../servidor/plasma/kit/getParametro',
                    method:"post",
                    params: {
                        id: Ext.getCmp('cbKitSuero1').getValue()
                    },
                    success: function( result, request ) {
                        var responseData = Ext.JSON.decode(result.responseText);
                        if(responseData.success)
                        {
                            values['casa_comercial']= responseData.data[0].casa_comercial;
                            Ext.Ajax.request({
                                url: '../servidor/plasma/pruebas/create',
                                method:"post",
                                params: {
                                    bandera:1,
                                    data: Ext.encode(values),
                                    muestra: ID
                                },
                                success: function( result, request ) {
                                    var responseData = Ext.JSON.decode(result.responseText);
                                    if(responseData.success)
                                    {
                                        Ext.Ajax.request({
                                            url: '../servidor/plasma/muestra/comprobarplasma',
                                            method:"post",
                                            params: {
                                                data: ID
                                            },
                                            success: function( result, request ) {
                                                var responseData = Ext.JSON.decode(result.responseText);
                                                if(responseData.estado_plasma === 'Completo')
                                                {
                                                    Ext.getCmp('tabPanel').down('#tab2').setDisabled(false);




                                                }
                                                else{
                                                    Ext.getCmp('tabPanel').down('#tab4').setDisabled(true);
                                                    Ext.getCmp('tabPanel').down('#tab3').setDisabled(true);
                                                }
                                            },

                                            failure: function(response, opts) {
                                                console.log('server-side failure with status code ' + response.status);
                                            }
                                        });



                                        Ext.Msg.alert('Aviso','Se ha ingresado la información');

                                        Ext.getCmp('frmPlasma').reset();
                                        var store = Ext.getStore('Pruebas');

                                        store.proxy.extraParams={
                                            bandera :2,
                                            id:ID
                                        };
                                        store.load();

                                    }
                                    else
                                    {
                                        Ext.Msg.alert('Alerta','Faltan datos');
                                    }
                                },

                                failure: function(response, opts) {
                                    console.log('server-side failure with status code ' + response.status);
                                }
                            });

                        }
                        else
                        {
                            Ext.Msg.alert('Alerta','Faltan datos');
                        }
                    },

                    failure: function(response, opts) {
                        console.log('server-side failure with status code ' + response.status);
                    }
                });
            }
            else
            {
                Ext.Msg.alert('Atención','Los datos son incorrectos o se encuentran incompletos');

            }
        }

    },

    onBtnEliminarSueroClick1: function(button, e, eOpts) {
        var g = Ext.getCmp('grdPruebasSuero1');
        var arrayKeys = g.getSelectionModel().selected.items;
        var indice = g.getSelectionModel().selectionStartIdx;
        if(arrayKeys.length === 0)
        Ext.Msg.alert('Error', 'Debe escoger un registro');
        else
        {
            var store = g.getStore();
            var rec = g.selection;
            store.remove(rec);
            store.sync(
            {
                params:{
                    id: rec.data.id
                },
                success: function(batch, success)
                {
                    store.commitChanges();
                    store.load();
                    Ext.Msg.alert('Alerta', 'Se ha eliminado el registro exitosamente');
                },

                failure: function(batch, success)
                {
                    Ext.Msg.alert('Error', 'Hubor un error');
                }
            });

        }
    },

    onRowEditingEdit: function(editor, context, eOpts) {
        var me = this;
        var store = Ext.getCmp('grdPruebasSuero1').getStore();
        var g = Ext.getCmp('grdPruebasSuero1');
        var reco = g.selection;
        var id = reco.data.muestra;
        var arrayKeys = g.getSelectionModel().selected.items;

        if (context.record.modified)
        {
            var reco = context.record;
            store.add(reco);
            store.sync(
            {
                params:{
                    id: id,
                    data: arrayKeys[0]
                },
                success: function(batch, success)
                {
                    store.commitChanges();
                    Ext.Msg.alert('Datos Guardados', 'Los datos se han guardado con éxito');
                    var strPruebas = Ext.getStore('Pruebas');
                    store.removeAll();
                    store.proxy.extraParams={
                        bandera: 2,
                        id: id

                    };
                    store.load();
                },

                failure: function(batch, success)
                {
                    Ext.Msg.alert('Error', 'Hubor un error');
                }
            });
        }
    },

    onPlasmaAfterRender: function(component, eOpts) {
        var store = Ext.getStore('Pruebas');

        store.proxy.extraParams={
            bandera :2,
            id:ID
        };
        store.load();
    },

    onCbStatusSelect: function(combo, record, eOpts) {
        if(Ext.getCmp('cbStatus').getValue() === '0'){
            Ext.getCmp('txtFechaTransformacion').setVisible(true);
            Ext.getCmp('txtObservacionT').setVisible(true);
            Ext.getCmp('txtLocalizacion').setVisible(false);
            Ext.getCmp('txtUbicacionSeroteca').setVisible(false);
            Ext.getCmp('txtVolumen').setVisible(false);
            Ext.getCmp('txtConcentracion').setVisible(false);

        }
        else if(Ext.getCmp('cbStatus').getValue() === '1'){
            Ext.getCmp('txtFechaTransformacion').setVisible(true);
            Ext.getCmp('txtLocalizacion').setVisible(true);
            Ext.getCmp('txtUbicacionSeroteca').setVisible(true);
            Ext.getCmp('txtVolumen').setVisible(true);
            Ext.getCmp('txtConcentracion').setVisible(true);
            Ext.getCmp('txtObservacionT').setVisible(false);
        }
        else if(Ext.getCmp('cbStatus').getValue() === '2'){
            Ext.getCmp('txtFechaTransformacion').setVisible(true);
            Ext.getCmp('txtObservacionT').setVisible(true);
            Ext.getCmp('txtLocalizacion').setVisible(false);
            Ext.getCmp('txtUbicacionSeroteca').setVisible(false);
            Ext.getCmp('txtVolumen').setVisible(false);
            Ext.getCmp('txtConcentracion').setVisible(false);
        }
        else if(Ext.getCmp('cbStatus').getValue() === '3'){
            Ext.getCmp('txtFechaTransformacion').setVisible(true);
            Ext.getCmp('txtObservacionT').setVisible(true);
            Ext.getCmp('txtLocalizacion').setVisible(false);
            Ext.getCmp('txtUbicacionSeroteca').setVisible(false);
            Ext.getCmp('txtVolumen').setVisible(false);
            Ext.getCmp('txtConcentracion').setVisible(false);
        }

    },

    onBtnGuardarMuestraClick1: function(button, e, eOpts) {

        if(ID === 'null'){
            Ext.Msg.alert('Aviso','Debe realizar primero la recepeción de la muestra');
        }
        else{
            var forma = Ext.getCmp('frmTransformacion').getForm();
            if (forma.isValid()) {
                var values = forma.getValues();


                Ext.Ajax.request({
                    url: '../servidor/plasma/muestra/updateMuestra',
                    method:"post",
                    params: {
                        muestra: ID,
                        data: Ext.encode(values)
                    },
                    success: function( result, request ) {
                        var responseData = Ext.JSON.decode(result.responseText);
                        if(responseData.success)
                        {
                            VOLUMEN = Ext.getCmp('txtVolumen').getValue();
                            Ext.Msg.alert('Aviso','Se ha ingresado la información');
                            Ext.getCmp('tabPanel').down('#tab3').setDisabled(false);
                        }
                        else
                        {
                            Ext.Msg.alert('Alerta','Faltan datos');
                        }
                    },

                    failure: function(response, opts) {
                        console.log('server-side failure with status code ' + response.status);
                    }
                });

            }
            else
            {
                Ext.Msg.alert('Alerta','Faltan datos');
            }

        }

    },

    onBtnCancelarMuestraClick1: function(button, e, eOpts) {
        if(!Ext.getCmp('pnlMuestras'))
        {
            Ext.getCmp('pnlCentral').removeAll();
            var win = Ext.create('plasma.view.pnlMuestras');
            Ext.getCmp('pnlCentral').add(win);
            win.show();
            var strMuestra = Ext.getStore('Muestra');
            strMuestra.removeAll();

            strMuestra.load();
        }
    },

    onTabActivate1: function(tab, eOpts) {
        var store = Ext.getStore('Pruebas');

        store.proxy.extraParams={
            bandera :1,
            id:ID
        };
        store.load();

        var strMarcador = Ext.getStore('Marcador');
        strMarcador.proxy.extraParams={
            bandera :1
        };
        strMarcador.load();

        var strKit = Ext.getStore('Kit');

        strKit.proxy.extraParams={
            bandera :1
        };
        strKit.load();
    },

    onSueroAfterRender: function(component, eOpts) {
        var store = Ext.getStore('Pruebas');

        store.proxy.extraParams={
            bandera :1,
            id:ID
        };
        store.load();
    },

    onBtnAgregarSueroClick: function(button, e, eOpts) {
        if(ID === 'null'){
            Ext.Msg.alert('Aviso','Debe realizar primero la recepción de la muestra');
        }
        else{
            var forma = Ext.getCmp('frmSuero').getForm(),
                store = Ext.getStore('Pruebas');
            if (forma.isValid()) {
                var values = forma.getValues();
                Ext.Ajax.request({
                    url: '../servidor/plasma/kit/getParametro',
                    method:"post",
                    params: {
                        id: Ext.getCmp('cbKitSuero').getValue()
                    },
                    success: function( result, request ) {
                        var responseData = Ext.JSON.decode(result.responseText);
                        if(responseData.success)
                        {
                            values['casa_comercial']= responseData.data[0].casa_comercial;
                            Ext.Ajax.request({
                                url: '../servidor/plasma/pruebas/create',
                                method:"post",
                                params: {
                                    data: Ext.encode(values),
                                    muestra: ID
                                },
                                success: function( result, request ) {
                                    var responseData = Ext.JSON.decode(result.responseText);
                                    if(responseData.success)
                                    {
                                        Ext.Ajax.request({
                                            url: '../servidor/plasma/muestra/comprobarsuero',
                                            method:"post",
                                            params: {
                                                data: ID
                                            },
                                            success: function( result, request ) {
                                                var responseData = Ext.JSON.decode(result.responseText);

                                                if(responseData.estado_suero === 'Completo')
                                                {
                                                    Ext.getCmp('tabPanel').down('#tab4').setDisabled(false);


                                                }
                                            },

                                            failure: function(response, opts) {
                                                console.log('server-side failure with status code ' + response.status);
                                            }
                                        });

                                        Ext.Msg.alert('Aviso','Se ha ingresado la información');

                                        Ext.getCmp('frmSuero').reset();
                                        var store = Ext.getStore('Pruebas');

                                        store.proxy.extraParams={
                                            bandera :1,
                                            id:ID
                                        };
                                        store.load();

                                    }
                                    else
                                    {
                                        Ext.Msg.alert('Alerta','Faltan datos');
                                    }
                                },

                                failure: function(response, opts) {
                                    console.log('server-side failure with status code ' + response.status);
                                }
                            });

                        }
                        else
                        {
                            Ext.Msg.alert('Alerta','Faltan datos');
                        }
                    },

                    failure: function(response, opts) {
                        console.log('server-side failure with status code ' + response.status);
                    }
                });
            }
            else
            {
                Ext.Msg.alert('Atención','Los datos son incorrectos o se encuentran incompletos');

            }
        }

    },

    onBtnEliminarSueroClick: function(button, e, eOpts) {
        var g = Ext.getCmp('grdPruebasSuero');
        var arrayKeys = g.getSelectionModel().selected.items;
        var indice = g.getSelectionModel().selectionStartIdx;
        if(arrayKeys.length === 0)
        Ext.Msg.alert('Error', 'Debe escoger un registro');
        else
        {
            var store = g.getStore();
            var rec = g.selection;
            store.remove(rec);
            store.sync(
            {
                params:{
                    id: rec.data.id
                },
                success: function(batch, success)
                {
                    store.commitChanges();
                    store.load();
                    Ext.Msg.alert('Alerta', 'Se ha eliminado el registro exitosamente');
                },

                failure: function(batch, success)
                {
                    Ext.Msg.alert('Error', 'Hubor un error');
                }
            });

        }
    },

    onRowEditingEdit1: function(editor, context, eOpts) {
        var me = this;
        var store = Ext.getCmp('grdPruebasSuero').getStore();
        var g = Ext.getCmp('grdPruebasSuero');
        var reco = g.selection;
        var id = reco.data.muestra;
        var arrayKeys = g.getSelectionModel().selected.items;

        if (context.record.modified)
        {
            var reco = context.record;
            store.add(reco);
            store.sync(
            {
                params:{
                    id: id,
                    data: arrayKeys[0]
                },
                success: function(batch, success)
                {
                    store.commitChanges();
                    Ext.Msg.alert('Datos Guardados', 'Los datos se han guardado con éxito');
                    var strPruebas = Ext.getStore('Pruebas');
                    store.removeAll();
                    store.proxy.extraParams={
                        id: id

                    };
                    store.load();
                },

                failure: function(batch, success)
                {
                    Ext.Msg.alert('Error', 'Hubor un error');
                }
            });
        }
    },

    onBtnAgregarSituacionClick: function(button, e, eOpts) {
        if(Ext.getCmp('txtVolumenSituacion').getValue()-Ext.getCmp('txtVolumenUsar').getValue()>=0){
            var forma = Ext.getCmp('frmSituacion').getForm(),
                store = Ext.getStore('Situacion');
            if (forma.isValid()) {
                var values = forma.getValues();
                Ext.Ajax.request({
                    url: '../servidor/plasma/situacion/create',
                    method:"post",
                    params: {
                        data: Ext.encode(values),
                        muestra: ID
                    },
                    success: function( result, request ) {
                        var responseData = Ext.JSON.decode(result.responseText);
                        if(responseData.success)
                        {

                            Ext.Ajax.request({
                                url: '../servidor/plasma/muestra/updateSituacion',
                                method:"post",
                                params: {
                                    volumen: Ext.getCmp('txtVolumenSituacion').getValue()-Ext.getCmp('txtVolumenUsar').getValue(),
                                    muestra: ID,
                                    situacion: Ext.getCmp('cbSituacionSituacion').getValue()
                                },
                                success: function( result, request ) {
                                    var responseData = Ext.JSON.decode(result.responseText);
                                    if(responseData.success)
                                    {

                                        Ext.Msg.alert('Aviso','Se ha ingresado la información');
                                        VOLUMEN = Ext.getCmp('txtVolumenSituacion').getValue()-Ext.getCmp('txtVolumenUsar').getValue();
                                        Ext.getCmp('frmSituacion').reset();
                                        var store = Ext.getStore('Situacion');

                                        store.proxy.extraParams={
                                            id:ID
                                        };
                                        store.load();

                                        Ext.getCmp('txtVolumenSituacion').setValue(VOLUMEN);

                                    }
                                    else
                                    {
                                        Ext.Msg.alert('Alerta','Faltan datos');
                                    }
                                },

                                failure: function(response, opts) {
                                    console.log('server-side failure with status code ' + response.status);
                                }
                            });

                        }
                        else
                        {
                            Ext.Msg.alert('Alerta','Faltan datos');
                        }
                    },

                    failure: function(response, opts) {
                        console.log('server-side failure with status code ' + response.status);
                    }
                });
            }
            else
            {
                Ext.Msg.alert('Atención','Los datos son incorrectos o se encuentran incompletos');

            }
        }
        else
        {
            Ext.Msg.alert('Atención','No hay volumen suficiente.');
        }
    },

    onBtnEliminarSituacionClick: function(button, e, eOpts) {
        var g = Ext.getCmp('grdSituacion');
        var arrayKeys = g.getSelectionModel().selected.items;
        var indice = g.getSelectionModel().selectionStartIdx;
        if(arrayKeys.length === 0)
        Ext.Msg.alert('Error', 'Debe escoger un registro');
        else
        {
            var store = g.getStore();
            var rec = g.selection;
            store.remove(rec);
            store.sync(
            {
                params:{
                    id: rec.data.id
                },
                success: function(batch, success)
                {
                    store.commitChanges();
                    store.load();
                    Ext.Msg.alert('Alerta', 'Se ha eliminado el registro exitosamente');
                },

                failure: function(batch, success)
                {
                    Ext.Msg.alert('Error', 'Hubor un error');
                }
            });

        }
    },

    onRowEditingEdit2: function(editor, context, eOpts) {
        var me = this;
        var store = Ext.getCmp('grdSituacion').getStore();
        var g = Ext.getCmp('grdSituacion');
        var reco = g.selection;
        var id = reco.data.muestra;
        var arrayKeys = g.getSelectionModel().selected.items;

        if (context.record.modified)
        {
            var reco = context.record;
            store.add(reco);
            console.log(reco);
            store.sync(
            {
                params:{
                    id: id,
                },
                success: function(batch, success)
                {
                    store.commitChanges();
                    Ext.Msg.alert('Datos Guardados', 'Los datos se han guardado con éxito');
                    var strSituacion = Ext.getStore('Situacion');
                    store.removeAll();
                    store.proxy.extraParams={
                        id: id

                    };
                    store.load();
                },

                failure: function(batch, success)
                {
                    Ext.Msg.alert('Error', 'Hubor un error');
                }
            });
        }
    },

    onSituacionAfterRender: function(component, eOpts) {
        var store = Ext.getStore('Situacion');

        store.proxy.extraParams={
            id:ID
        };
        store.load();
        Ext.getCmp('txtVolumenSituacion').setValue(VOLUMEN);

    }

});
