/*
 * File: app/view/pnlUsuarios.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('plasma.view.pnlUsuarios', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.pnlusuarios',

    requires: [
        'plasma.view.pnlUsuariosViewModel',
        'plasma.view.pnlUsuariosViewController',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Check',
        'Ext.form.field.Checkbox',
        'Ext.form.field.ComboBox',
        'Ext.grid.column.Template',
        'Ext.XTemplate',
        'Ext.grid.plugin.RowEditing'
    ],

    controller: 'pnlusuarios',
    viewModel: {
        type: 'pnlusuarios'
    },
    layout: 'fit',
    title: 'Usuarios',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    id: 'btnNuevoUs',
                    iconAlign: 'right',
                    iconCls: 'x-fa fa-plus',
                    text: 'Nuevo',
                    listeners: {
                        click: 'onBtnNuevoUsClick'
                    }
                },
                {
                    xtype: 'button',
                    id: 'btnEliminarUs',
                    iconAlign: 'right',
                    iconCls: 'x-fa fa-trash',
                    text: 'Eliminar',
                    listeners: {
                        click: 'onBtnEliminarUsClick'
                    }
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'gridpanel',
            id: 'grdUsuarios',
            title: '',
            forceFit: true,
            store: 'Usuario',
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'usuario',
                    text: 'Usuario'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'cedula',
                    text: 'Cedula',
                    editor: {
                        xtype: 'textfield'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'nombre',
                    text: 'Nombre',
                    editor: {
                        xtype: 'textfield'
                    }
                },
                {
                    xtype: 'checkcolumn',
                    disabled: true,
                    dataIndex: 'estado',
                    text: 'Estado',
                    editor: {
                        xtype: 'checkboxfield'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        if(view)
                        {
                            var descripcion = record.data.rol;
                            var combo = metaData.column.getEditor();
                            var comboStore = combo.getStore();
                            var indice = comboStore.findExact(combo.valueField, value);
                            if (indice >= 0)
                            return comboStore.getAt(indice).get(combo.displayField);
                            else
                            return descripcion;
                        }
                        else
                        return null;
                    },
                    dataIndex: 'rol',
                    text: 'Rol',
                    editor: {
                        xtype: 'combobox',
                        id: 'cbRol',
                        editable: false,
                        displayField: 'descripcion',
                        queryMode: 'local',
                        store: 'Rol',
                        valueField: 'id'
                    }
                },
                {
                    xtype: 'templatecolumn',
                    tpl: [
                        '<a href="mailto:{email}">{email}</a>'
                    ],
                    dataIndex: 'email',
                    text: 'Email',
                    editor: {
                        xtype: 'textfield'
                    }
                }
            ],
            plugins: [
                {
                    ptype: 'rowediting',
                    listeners: {
                        edit: 'onRowEditingEdit'
                    }
                }
            ]
        }
    ]

});