/*
 * File: app/view/wndCodigoViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('plasma.view.wndCodigoViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.wndcodigo',

    onBtnCrearCodClick: function(button, e, eOpts) {
        var me = this;
        var forma = Ext.getCmp('frmNuevoCod').getForm(),
            store = Ext.getStore('Codigo');
        if (forma.isValid()) {
            var values = forma.getValues();
            Ext.Ajax.request({
                url: '../servidor/plasma/codigomapa/create',
                method:"post",
                params: {
                    data: Ext.encode(values)
                },
                success: function( result, request ) {
                    var responseData = Ext.JSON.decode(result.responseText);
                    if(responseData.success)
                    {

                        Ext.Msg.alert('Aviso','Se ha ingresado la información');
                        Ext.getCmp('txtNombreC').setValue(null);
                        Ext.getCmp('cbEstadoC').setValue(null);

                        Ext.getCmp('txtNombreC').reset();
                        Ext.getCmp('cbEstadoC').reset();

                        store.load();
                        Ext.getCmp('wndCodigo').close();




                    }
                    else
                    {
                        Ext.Msg.alert('Alerta','Faltan datos');
                    }
                },

                failure: function(response, opts) {
                    console.log('server-side failure with status code ' + response.status);
                }
            });
        }
        else
        {
            Ext.Msg.alert('Atención','Los datos son incorrectos o se encuentran incompletos');

        }
    },

    onBtnRegresarCodClick: function(button, e, eOpts) {
        Ext.getCmp('wndCodigo').close();
    }

});
