/*
 * File: app/view/wndKitViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('plasma.view.wndKitViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.wndkit',

    onBtnCrearKitClick: function(button, e, eOpts) {
        var me = this;
        var forma = Ext.getCmp('frmNuevoKit').getForm(),
            store = Ext.getStore('Kit');
        if (forma.isValid()) {
            Ext.Ajax.request({
                url: '../servidor/plasma/kit/verificakit',
                method:"post",
                params: {
                    nombre: Ext.getCmp('txtNombreK').getValue(),
                    casa: Ext.getCmp('cbCasaK').getValue()

                },
                success: function( result, request ) {
                    var responseData = Ext.JSON.decode(result.responseText);
                    if(responseData.success){
                        var values = forma.getValues();
                        Ext.Ajax.request({
                            url: '../servidor/plasma/kit/create',
                            method:"post",
                            params: {
                                data: Ext.encode(values)
                            },
                            success: function( result, request ) {
                                var responseData = Ext.JSON.decode(result.responseText);
                                if(responseData.success)
                                {

                                    Ext.Msg.alert('Aviso','Se ha ingresado la información');
                                    Ext.getCmp('cbCasaK').setValue(null);
                                    Ext.getCmp('txtNombreK').setValue(null);
                                    Ext.getCmp('cbEstadoK').setValue(null);


                                    Ext.getCmp('cbCasaK').reset();
                                    Ext.getCmp('txtNombreK').reset();
                                    Ext.getCmp('cbEstadoK').reset();

                                    store.load();
                                    Ext.getCmp('wndKit').close();




                                }
                                else
                                {
                                    Ext.Msg.alert('Alerta','Faltan datos');
                                }
                            },

                            failure: function(response, opts) {
                                console.log('server-side failure with status code ' + response.status);
                            }
                        });
                    }
                    else{
                        Ext.Msg.alert('Atención','El kit con la casa comercial seleccionada ya existe');
                    }
                }
            });
        }
        else
        {
            Ext.Msg.alert('Atención','Los datos son incorrectos o se encuentran incompletos');

        }
    },

    onBtnRegresarKitClick: function(button, e, eOpts) {
        Ext.getCmp('wndKit').close();
    }

});
