/*
 * File: app/view/wndUsuario.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('plasma.view.wndUsuario', {
    extend: 'Ext.window.Window',
    alias: 'widget.wndusuario',

    requires: [
        'plasma.view.wndUsuarioViewModel',
        'plasma.view.wndUsuarioViewController',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.button.Button'
    ],

    controller: 'wndusuario',
    viewModel: {
        type: 'wndusuario'
    },
    modal: true,
    height: 366,
    id: 'wndUsuario',
    width: 400,
    layout: 'center',
    title: 'Usuario',

    items: [
        {
            xtype: 'form',
            id: 'frmNuevoUs',
            bodyPadding: 10,
            title: '',
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    id: 'txtUsuario',
                    fieldLabel: 'Usuario',
                    labelStyle: 'font-weight:bold',
                    labelWidth: 110,
                    name: 'usuario',
                    allowBlank: false,
                    emptyText: 'Ingrese en mayúsculas',
                    maskRe: /^[A-Z0-9]/
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    id: 'txtCedula',
                    fieldLabel: 'Cedula/Pasaporte',
                    labelStyle: 'font-weight:bold',
                    labelWidth: 110,
                    name: 'cedula',
                    allowBlank: false
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    id: 'txtNombre',
                    fieldLabel: 'Nombre',
                    labelStyle: 'font-weight:bold',
                    labelWidth: 110,
                    name: 'nombre',
                    allowBlank: false,
                    maskRe: /^[A-Za-z]/
                },
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    id: 'cbEstado',
                    fieldLabel: 'Estado',
                    labelStyle: 'font-weight:bold',
                    labelWidth: 110,
                    name: 'estado',
                    allowBlank: false,
                    editable: false,
                    displayField: 'descripcion',
                    queryMode: 'local',
                    store: 'Estado',
                    valueField: 'id'
                },
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    id: 'cbRolUs',
                    fieldLabel: 'Rol',
                    labelStyle: 'font-weight:bold',
                    labelWidth: 110,
                    name: 'rol',
                    allowBlank: false,
                    editable: false,
                    displayField: 'descripcion',
                    queryMode: 'local',
                    store: 'Rol',
                    valueField: 'id'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    id: 'txtEmail',
                    fieldLabel: 'Email',
                    labelStyle: 'font-weight:bold',
                    labelWidth: 110,
                    name: 'email',
                    inputType: 'email',
                    allowBlank: false,
                    vtype: 'email'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            id: 'btnCrearUs',
                            text: 'Crear',
                            listeners: {
                                click: 'onBtnCrearUsClick'
                            }
                        },
                        {
                            xtype: 'button',
                            id: 'btnRegresarUs',
                            text: 'Atrás',
                            listeners: {
                                click: 'onBtnRegresarUsClick'
                            }
                        },
                        {
                            xtype: 'tbfill'
                        }
                    ]
                }
            ]
        }
    ]

});