/*
 * File: app/model/Muestra_Model.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('plasma.model.Muestra_Model', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Date',
        'Ext.data.field.Number'
    ],

    fields: [
        {
            type: 'int',
            name: 'id'
        },
        {
            type: 'string',
            name: 'descripcion'
        },
        {
            type: 'date',
            name: 'fecha_ingreso',
            dateFormat: 'Y-m-d'
        },
        {
            type: 'date',
            name: 'fecha_modificacion',
            dateFormat: 'Y-m-d'
        },
        {
            type: 'date',
            name: 'fecha_recepcion',
            dateFormat: 'Y-m-d'
        },
        {
            type: 'date',
            name: 'fecha_transformacion',
            dateFormat: 'Y-m-d'
        },
        {
            type: 'date',
            name: 'fecha_caracterizacion',
            dateFormat: 'Y-m-d'
        },
        {
            type: 'int',
            name: 'institucion'
        },
        {
            type: 'int',
            name: 'kit'
        },
        {
            type: 'string',
            name: 'localizacion_transformacion'
        },
        {
            type: 'int',
            name: 'marcador'
        },
        {
            type: 'string',
            name: 'observacion'
        },
        {
            type: 'string',
            name: 'resultado'
        },
        {
            type: 'string',
            name: 'situacion'
        },
        {
            type: 'string',
            name: 'estatus'
        },
        {
            type: 'string',
            name: 'ubicacion'
        },
        {
            type: 'string',
            name: 'ubicacion_plasmoteca'
        },
        {
            type: 'string',
            name: 'ubicacion_seroteca'
        },
        {
            type: 'float',
            name: 'volumen'
        },
        {
            type: 'string',
            name: 'usuario_recepcion'
        },
        {
            type: 'string',
            name: 'usuario_trasnformacion'
        },
        {
            type: 'string',
            name: 'estado_plasma'
        },
        {
            type: 'string',
            name: 'estado_suero'
        },
        {
            type: 'float',
            name: 'concentracion_calcio'
        }
    ]
});