/*
 * File: app/view/wndCasaViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('plasma.view.wndCasaViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.wndcasa',

    onBtnCrearCasaClick: function(button, e, eOpts) {
        var me = this;
        var forma = Ext.getCmp('frmNuevoCasa').getForm(),
            store = Ext.getStore('Casa');
        if (forma.isValid()) {
            Ext.Ajax.request({
                url: '../servidor/plasma/casacomercial/verificacasa',
                method:"post",
                params: {
                    nombre: Ext.getCmp('txtNombreCa').getValue()

                },
                success: function( result, request ) {
                    var responseData = Ext.JSON.decode(result.responseText);
                    if(responseData.success){
                        var values = forma.getValues();
                        Ext.Ajax.request({
                            url: '../servidor/plasma/casacomercial/create',
                            method:"post",
                            params: {
                                data: Ext.encode(values)
                            },
                            success: function( result, request ) {
                                var responseData = Ext.JSON.decode(result.responseText);
                                if(responseData.success)
                                {

                                    Ext.Msg.alert('Aviso','Se ha ingresado la información');
                                    Ext.getCmp('txtNombreCa').setValue(null);
                                    Ext.getCmp('cbEstadoCa').setValue(null);

                                    Ext.getCmp('txtNombreCa').reset();
                                    Ext.getCmp('cbEstadoCa').reset();

                                    store.load();
                                    Ext.getCmp('wndCasa').close();




                                }
                                else
                                {
                                    Ext.Msg.alert('Alerta','Faltan datos');
                                }
                            },

                            failure: function(response, opts) {
                                console.log('server-side failure with status code ' + response.status);
                            }
                        });
                    }
                    else{
                        Ext.Msg.alert('Atención','La casa comercial ya existe');
                    }

                }

            });

        }
        else
        {
            Ext.Msg.alert('Atención','Los datos son incorrectos o se encuentran incompletos');

        }
    },

    onBtnAtrasCClick: function(button, e, eOpts) {
        Ext.getCmp('wndCasa').close();
    }

});
