/*
 * File: app/view/wndMarcador.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('plasma.view.wndMarcador', {
    extend: 'Ext.window.Window',
    alias: 'widget.wndmarcador',

    requires: [
        'plasma.view.wndMarcadorViewModel',
        'plasma.view.wndMarcadorViewController',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.button.Button'
    ],

    controller: 'wndmarcador',
    viewModel: {
        type: 'wndmarcador'
    },
    modal: true,
    height: 250,
    id: 'wndMarcador',
    width: 400,
    layout: 'center',
    title: 'Marcador Serológico',

    items: [
        {
            xtype: 'form',
            id: 'frmNuevoMar',
            bodyPadding: 10,
            title: '',
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    id: 'txtNombreM',
                    fieldLabel: 'Nombre',
                    labelStyle: 'font-weight:bold',
                    name: 'nombre',
                    allowBlank: false
                },
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    id: 'cbEstadoM',
                    fieldLabel: 'Estado',
                    labelStyle: 'font-weight:bold',
                    name: 'estado',
                    allowBlank: false,
                    editable: false,
                    displayField: 'descripcion',
                    queryMode: 'local',
                    store: 'Estado',
                    valueField: 'id'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            id: 'btnCrearMar',
                            text: 'Crear',
                            listeners: {
                                click: 'onBtnCrearMarClick'
                            }
                        },
                        {
                            xtype: 'button',
                            id: 'btnRegresarMar',
                            text: 'Atrás',
                            listeners: {
                                click: 'onBtnRegresarMarClick'
                            }
                        },
                        {
                            xtype: 'tbfill'
                        }
                    ]
                }
            ]
        }
    ]

});