/*
 * File: app/view/wndPdfViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('plasma.view.wndPdfViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.wndpdf',

    onBtnGenerarClick: function(button, e, eOpts) {
        var forma = Ext.getCmp('frmPdf').getForm();
        var values = forma.getValues();
        if (forma.isValid()) {
            Ext.Ajax.request
            (
            {
                method: 'post',
                url: '../servidor/plasma/registro/getReporte',
                params: {
                    id: ID,
                    data: Ext.encode(values)
                    //parametro: arrayKeys[0].data.TRA_PRM_ID,
                },
                success: function(response){
                    var _url = response.responseText;
                    new Ext.Window({
                        title: 'Plasma',
                        id: 'pdfWindow',
                        layout: 'fit',
                        width: 800,
                        height: 700,
                        modal: true,
                        closeAction: 'destroy',
                        items: [{
                            xtype: 'component',
                            autoEl: {
                                tag: 'iframe',
                                style: 'height:100%; width:100%; border:none',
                                src: _url
                            }
                        }]
                    }).show();
                }
            }
            );
        }
        else
        {
            Ext.Msg.alert('Atención','Los datos son incorrectos o se encuentran incompletos');
        }
    },

    onBtnCancelarPdfClick: function(button, e, eOpts) {
        Ext.getCmp('wndPdf').close();
    }

});
