/*
 * File: app/model/Pruebas_Model.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('plasma.model.Pruebas_Model', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Number',
        'Ext.data.field.Date'
    ],

    fields: [
        {
            type: 'string',
            name: 'marcador'
        },
        {
            type: 'string',
            name: 'kit'
        },
        {
            type: 'string',
            name: 'casa_comercial'
        },
        {
            type: 'float',
            name: 'valor'
        },
        {
            type: 'string',
            name: 'lote'
        },
        {
            type: 'date',
            name: 'fecha_caducidad',
            dateFormat: 'Y-m-d',
            dateReadFormat: 'Y-m-d',
            dateWriteFormat: 'Y-m-d'
        },
        {
            type: 'string',
            name: 'usuario'
        },
        {
            type: 'string',
            name: 'orden'
        },
        {
            type: 'string',
            name: 'interpretacion'
        },
        {
            type: 'float',
            name: 'id'
        },
        {
            type: 'float',
            name: 'tipo'
        },
        {
            type: 'float',
            name: 'muestra'
        },
        {
            type: 'date',
            name: 'fecha_caracterizacion',
            dateFormat: 'Y-m-d',
            dateReadFormat: 'Y-m-d',
            dateWriteFormat: 'Y-m-d'
        }
    ]
});